nextflow run ./main.nf \
  -profile singularity \
  -work-dir /media/baseripper/volume_28TB_1/workFolder_MetaRun/work \
  --reads /media/baseripper/volume_28TB_1/rawdata_P11065 \
  --outdir /media/baseripper/volume_28TB_1/metalOutput/run_P11065 \
  --max_cpus 56 \
  --max_mem 250.GB \
  --run_trimgalore false \
  --run_ribodetector false \
  --run_sortmerna false \
  --run_kraken2 false \
  --run_parabricks false \
  --run_star true \
  --run_featurecounts true \
  --run_salmon false \
  --skip_fastqc_raw true \
  --skip_fastqc_trimmed true \
  --skip_multiqc_trimmed true \
  --skip_fastqc_ribo true \
  --skip_multiqc_ribo true \
  --star_index /media/baseripper/2TB_Baseripper/Stef/V0.1.1_MetaLL/MetaLL_0.0.1/assets/GRCh38_indexed \
  --genome_gtf /media/baseripper/2TB_Baseripper/Stef/V0.1.1_MetaLL/MetaLL_0.0.1/assets/GRCh38_indexed/gencode.v44.annotation.gtf \
  -resume